//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIVALE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public long LAST_UPDATED { get; set; }
        public System.DateTime DATE_TIME { get; set; }
        public string DATE { get; set; }
        public string TIME_OF_DATE_TIME { get; set; }
        public int CURSOR { get; set; }
        public int CATEGORY { get; set; }
        public int SMART_GATEWAY_ID { get; set; }
        public Nullable<int> DEVICE_IDENTIFIER { get; set; }
        public Nullable<int> FLC_ALARM_HISTORY_TYPE { get; set; }
        public Nullable<int> DOOR_NO { get; set; }
        public Nullable<int> CR_NO { get; set; }
        public string CARD_NO { get; set; }
        public Nullable<int> EVENT_TYPE_NO { get; set; }
        public Nullable<int> EVENT_FACTOR_NO { get; set; }
        public Nullable<int> SEQUENCE_NO { get; set; }
        public Nullable<int> OBJECT_IDENTIFIER { get; set; }
        public Nullable<int> FMC_ALARM_HISTORY_TYPE { get; set; }
        public Nullable<int> UNSIGNED_EVENT_VALUE { get; set; }
        public Nullable<int> FEEDBACK_VALUE { get; set; }
        public Nullable<double> ANALOG_EVENT_VALUE { get; set; }
        public Nullable<double> ANALOG_DEADBAND { get; set; }
        public Nullable<double> ANALOG_EXCEEDED_LIMITED { get; set; }
        public Nullable<int> ACCUMULATOR_EXCEEDED_LIMITED { get; set; }
        public Nullable<bool> IN_ALARM { get; set; }
        public string STATUS_FLAGS { get; set; }
        public Nullable<int> COMMANDER { get; set; }
        public string COMMANDER_TEXT { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string SITE_GR_ID { get; set; }
        public string SITE_GR_NAME { get; set; }
        public string SITE_NAME { get; set; }
        public Nullable<int> SITE_ID { get; set; }
        public string TENANT_GR_ID { get; set; }
        public string TENANT_ID { get; set; }
        public string TENANT_NAME { get; set; }
        public string EQUIPMENT_GR_ID { get; set; }
        public string EQUIPMENT_GR_NAME { get; set; }
        public string EQUIPMENT_NAME1 { get; set; }
        public string EQUIPMENT_NAME2 { get; set; }
        public string EVENT_MESSAGE { get; set; }
        public string EVENT_TEXT { get; set; }
        public Nullable<System.DateTime> DESCRIPTION_DATE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.DateTime> CONTROL_CENTER_DESCRIPTION_DATE { get; set; }
        public string CONTROL_CENTER_DESCRIPTION { get; set; }
        public string DESCRIPTION { get; set; }
        public string MANAGEMENT_CODE { get; set; }
        public Nullable<int> PERSON_ID { get; set; }
        public string PERSON_NAME { get; set; }
        public Nullable<int> CARD_ID { get; set; }
        public string CARD_FACE_NO { get; set; }
        public Nullable<int> CARD_CATEGORY { get; set; }
        public string CARD_ROOM { get; set; }
        public string CARD_DESCRIPTION { get; set; }
        public Nullable<int> CREDENTIAL_READER_ID { get; set; }
        public string BRANCH_CODE { get; set; }
        public string MANAGE_NO { get; set; }
        public string CONTROLLER_CODE { get; set; }
        public string SERVICE_TEXT { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> VALUES_OWNER_ID { get; set; }
        public string CAMERA_ID_LIST { get; set; }
        public string PERSON_GR_ID { get; set; }
        public string PERSON_GR_NAME { get; set; }
        public string CREDENTIAL_GR_ID { get; set; }
        public string CREDENTIAL_GR_NAME { get; set; }
        public string SCREEN_NAME { get; set; }
        public string OPERATION { get; set; }
        public Nullable<bool> RESULT { get; set; }
        public Nullable<int> USERS_ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string USERS_NAME { get; set; }
        public string USERS_GR_ID { get; set; }
        public string USERS_GR_NAME { get; set; }
        public string PERSON_NODE_PATH { get; set; }
        public string CREDENTIAL_NODE_PATH { get; set; }
        public string EQUIPMENT_POINT_NODE_PATH { get; set; }
        public string TENANT_NODE_PATHS { get; set; }
        public string USER_OPERATION_NODE_PATH { get; set; }
        public string TAG { get; set; }
        public Nullable<int> POINT_NO { get; set; }
        public Nullable<int> ALARM_PRIORITY { get; set; }
        public Nullable<int> LINE_TYPE { get; set; }
        public Nullable<int> ACTING_FLAG { get; set; }
        public Nullable<int> BUILDING_MANAGEMENT_ALARM_FLAG { get; set; }
        public Nullable<int> DISTRIBUTION_PATTERN { get; set; }
    }
}
