//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIVALE.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodePermission
    {
        public int Id { get; set; }
        public int PERMISSION_OWNER_ID { get; set; }
        public int PERMISSION_OWNER_TYPE { get; set; }
        public string NODE_PATH { get; set; }
        public int PERMISSION_LEVEL { get; set; }
    
        public virtual User User { get; set; }
    }
}
