CREATE TABLE [dbo].[History]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [LAST_UPDATED] BIGINT NULL, 
    [DATE_TIME] DATE NULL, 
    [DATE] NVARCHAR(50) NULL, 
    [TIME_OF_DATE_TIME] NVARCHAR(50) NULL, 
    [CURSOR] INT NULL, 
    [CATEGORY] INT NULL, 
    [SMART_GATEWAY_ID] INT NULL, 
    [DEVICE_IDENTIFIER] INT NULL, 
    [FLC_ALARM_HISTORY_TYPE] INT NULL, 
    [DOOR_NO] INT NULL, 
    [CR_NO] INT NULL, 
    [CARD_NO] NVARCHAR(50) NULL, 
    [EVENT_TYPE_NO] INT NULL, 
    [EVENT_FACTOR_NO] INT NULL, 
    [SEQUENCE_NO] INT NULL, 
    [OBJECT_IDENTIFIER] INT NULL
)
