CREATE TABLE [dbo].[UserGroup]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NAME] NVARCHAR(40) NULL, 
    [HOMEPAGE_URL] NVARCHAR(100) NULL, 
    [DEFAULT_PASSWORD_VALID_TERM] INT NULL, 
    [PARENT_ID] INT NULL, 
    [HIERARCHY_DEPTH] INT NOT NULL, 
    [NODE_PATH] NVARCHAR(300) NULL, 
    [USER_GR_CODE] NVARCHAR(30) NULL, 
    [USERS_GR_TYPE] INT NULL, 
    [MAX_USER_COUNT] INT NULL
)
