CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [LOGIN_NAME] NVARCHAR(200) NULL, 
    [USER_TYPE] INT NULL, 
    [PASSWORD1 ] NVARCHAR(50) NULL, 
    [PASSWORD2] NVARCHAR(50) NULL, 
    [AUTHENTICATION_CODE] NVARCHAR(160) NULL, 
    [PARENT_ID] INT NULL, 
    [NAME] NVARCHAR(500) NULL, 
    [POSITION] NVARCHAR(400) NULL, 
    [DESCRIPTION] NVARCHAR(40) NULL, 
    [EDIT_FORBIDDEN] INT NULL, 
    [MAIL_ADDRESS] NVARCHAR(2550) NULL, 
    [PASSWORD_EXPIRATION_TERM] INT NULL, 
    [PASSWORD_UPDATE_NOTIFICATION] INT NULL, 
    [PASSWORD_UPDATE_DATE] DATE NULL, 
    [HISTORY_DOWNLOAD_NOTIFICATION] INT NULL
)
